FROM nginx:1.27.1-alpine3.20

RUN apk update

RUN apk add --no-cache openssl=3.3.2-r0

# Config to create self-signed key and certificate
RUN mkdir -p /etc/nginx/ssl && \
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/nginx/ssl/selfsigned.key \
    -out /etc/nginx/ssl/selfsigned.crt \
    -subj "/C=BR/ST=Piauí/L=Parnaíba/O=BirthdayReminder/OU=IT/CN=nginx"
