services:
  web:
    container_name: web
    build: .
    env_file:
      - .env
    command: "python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    networks:
      - birthday_api
    depends_on:
      - broker
  
  broker:
    container_name: broker
    image: rabbitmq:3.13.7-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=$RABBITMQ_USER
      - RABBITMQ_DEFAULT_PASS=$RABBITMQ_PASS

networks:
  birthday_api:
    name: birthday_api
