services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    command: "gunicorn -c gunicorn.prod.conf.py"
    volumes:
      - ./app:/app

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app:/app
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
