services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    command: "gunicorn -c gunicorn.prod.conf.py"
    ports:
      - 8000:8000
    volumes:
      - ./app:/app

  nginx:
    image: nginx:1.27.1-alpine3.20
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./app:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
