# Generated by Django 4.2.11 on 2024-05-11 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_member_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manager",
            name="member_info",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.member",
            ),
        ),
    ]
